### ISSUE TITLE
Annotations: test set 

### ISSUE THREAD

**Issue by fabienbaradel** [epic-kitchens/annotations#1]
Hi,

Thanks for the release of this dataset, this is absolutely awesome for the community.
When do you plan to release the annotations for the test set? Or at least open the leaderboard?
Thanks,
Best

**Comment by dimadamen** [comment]
Thanks for your inquiry. The test set annotations will not be disclosed, but the evaluation protocol to submit your test results and the leaderboard will be opened beginning of July. This is planned after CVPR where a demonstration of the dataset is scheduled. We invite early adopters, people who would like to test a beta version of the leaderboard. If you are interested in testing the beta version, send us a contact email, and the challenge(s) you're interested in to: uob-epic-kitchens2018@bristol.ac.uk

**Comment by fabienbaradel** [comment]
Thanks @dimadamen for your answer. I am looking forward your demonstration at CVPR.
I am contacting you by email for testing a beta version of the leaderboard.
