### ISSUE TITLE
Submission failed

### ISSUE THREAD

**Issue by ryosism** [epic-kitchens/annotations#15]
I've finished training with your train dataset, and testing the detection with test video frame.
Once I've submitted my detection result to [CodaLab](https://competitions.codalab.org/competitions/20111#learn_the_details), an error occurred `ValueError: Image: P01_12_2761 has 0 bounding boxes not 300`.

In my inference by trained model, no bounding boxes were detected in `P01_12/0000002761.jpg`.   
So please tell me how to output the result for no-bounding boxes in JSON object?

Best,

**Comment by hazeld** [comment]
Hi ryosism,

The codalab object recognition evaluation should now handle submitting 0 detected boxes for an image. Please use the same JSON format as you did previously, i.e. don't include an entry for images with no detections.

**Comment by ryosism** [comment]
I confirmed 4th submission and its status was finished. Thanks a lot!
