### ISSUE TITLE
Can you share Faster R-CNN baseline model parameters?

### ISSUE THREAD

**Issue by Horacehxw** [epic-kitchens/annotations#18]
Hi, is it possible for you to share the Faster R-CNN model parameters mentioned in the paper? I want to use it as a baseline and a teacher network for other tasks. Thank you!

**Comment by hazeld** [comment]
Hi,
We've now made the trained Faster R-CNN model publicly available here: https://data.bris.ac.uk/data/dataset/gw5q146a9dqd2t82jhu8noe3m
I hope this is useful!
