### ISSUE TITLE
Object Detection Submission Failed

### ISSUE THREAD

**Issue by gberta** [epic-kitchens/annotations#22]
As recommended on CodaLab website, for the object detection challenge, I'm submitting 300 boxes per image (each of them rounded to 5 decimals). However, my submission fails without  providing any qualitative errors. Here's the text from the log of the submission file:

elapsedTime: 93.22970509529114
exitCode: 137
ingestionExitCode: 0

or another one that took much longer to fail:

elapsedTime: 8046.879673957825
exitCode: 137
ingestionExitCode: 0

I have successfully evaluated some submissions before. However, I noticed that sometimes the submissions fail, if there are too many bounding boxes included (even if it's < 300 boxes per image). How do I fix this issue?

I also noticed that sometimes I get "Execution time limit exceeded!" error.

**Comment by gberta** [comment]
Would it also be possible to provide sample json submission files (i.e. from a pretrained Faster R-CNN model) for a reference?

**Comment by yassersouri** [comment]
@tridivb Is this the same problem you had?

**Comment by tridivb** [comment]
Yes. The max number bounding boxes that I have been able to submit are 125.
