### ISSUE TITLE
How can I perform action recognition experiments on a subset of the published test data?

### ISSUE THREAD

**Issue by AntonyPapadakis** [epic-kitchens/annotations#28]
Hello there! Thank you for creating and maintaining a great project! 
In my case I am working with a subset ,i.e., some of the kitchens, of the epic-kitchens-55 dataset. I think I need ground truth test action labels, since I am not using the entire dataset to perform my experiments. Basically, I want to calculate accuracy on the actions from certain kitchens and not the whole dataset, so I guess the epic-55 leaderboard option will not do. How can I get the the test accuracy in my case using a subset of the published test data?

**Comment by dimadamen** [comment]
The test set is not going to be released because it is part of the challenge leaderboard.
We cannot release subsets of these. You can use the "validation" split of EPIC-KITCHENS-100 to do the sort of thing you're talking about.
