### ISSUE TITLE
Request to participate in EPIC-KITCHENS-55 Object Detection but no response.

### ISSUE THREAD

**Issue by wullia** [epic-kitchens/annotations#29]
Whether the review is still in progress?  I have submit my request to participate in EPIC-KITCHENS-55 two days ago but recieve no response till now.

**Comment by wullia** [comment]
If the competetion is over, could you please upload the object detection annotation of s1 and s2?

**Comment by dimadamen** [comment]
There's no *valid* participant application on Codalab. Note that we only accept applications from institution emails (i.e. no gmail, yahoo, qq, ...).
If you have submitted a valid request and have not heard back, please email: uob-epic-kitchens@bristol.ac.uk
