### ISSUE TITLE
Concerning the separate parts of the dataset

### ISSUE THREAD

**Issue by Linardos** [epic-kitchens/annotations#3]
You mention that "Due to the size of the dataset we provide three scripts for downloading the videos, frames or object annotation images separately". Would it be possible to display the size of each of these separate parts of the dataset?
I am interested in applying a model to extract saliency maps from your data, but the 1TB is too large in size and also to compute, potentially.

**Comment by mwray** [comment]
Videos have a size of ~750GB, The frames have a size of ~320GB and the Object detection images have a size of ~80GB.
