### ISSUE TITLE
How to apply to participate in the EPIC-KITCHENS-55 Object Detection leaderboard？

### ISSUE THREAD

**Issue by chenchen0811** [epic-kitchens/annotations#31]
Hello, I have applied to participate in the EPIC-KITCHENS-55 Object Detection leaderboard and would like to test on the EPIC-KITCHENS-55 test set. 
The CodaLab website shows "Your request to participate in this challenge has been received and a decision is pending.", but I have not received a response for a long time.
I can't find the ground truth file of test dataset in this repository and the competition EPIC-KITCHENS-55 Object Detection has ended, so how can I get the test accuracy of action recognition benchmark? I want to get the test accuracy of my model both on epic-kitchens-55  datasets.

**Comment by dimadamen** [comment]
epic-kitchens-55 action recognition is NOT a valid challenge any longer, as the hidden test set was released as part of the validation set for epic-kitchens-100. This means this test set is already disclosed and accordingly no leaderboard/benchmark should be used. Please use the epic-kitchens-100 action recognition challenge instead.

We can help you with the object detection challenge if you need, but the recognition challenge is certainly no longer valid.

**Comment by chenchen0811** [comment]
Thank you for your response! 
Could you please provide the annotation files for the EPIC-KITCHENS-55 Object Detection test set? 
Could you provide a downloadable link, or could you email them to me? My email address is chen981227@126.com.
Thank you so much!

**Comment by chenchen0811** [comment]
Hello, I have applied to participate in the EPIC-KITCHENS-55 Object Detection leaderboard, can you pass my application￼
![图片 1](https://github.com/epic-kitchens/epic-kitchens-55-annotations/assets/31870528/4aadc35d-64a8-4dfa-a954-a28b9fe9c19d)

**Comment by dimadamen** [comment]
This is not an ongoing challenge. It has closed a while ago and is no longer maintained as you can see in the dates.

**Comment by chenchen0811** [comment]
So, could you please provide the annotation files of the EPIC-KITCHENS-55 Object Detection test set for evaluation purposes?
I can't find the ground truth file of test datasets in this repository.
Thank you!

**Comment by dimadamen** [comment]
Sent to you by email.

**Comment by AKASH2907** [comment]
Hi, Can I also please get the test set for object detection EPIC-Kitchens 55? Thanks.
