### ISSUE TITLE
Intersection between object detection and action recognition tasks

### ISSUE THREAD

**Issue by victorhcm** [epic-kitchens/annotations#5]
Do you have any statistics of how many samples we would have if we wanted the ones that had both object and action annotations?

**Comment by willprice** [comment]
Hi @victorhcm 
We don't have any statistics to hand, but I believe object detection frames were sampled every 1/2s for 2s around each action segment. I'll let @hazeld provide a definitive answer for this one as I wasn't involved in the object annotations. 
Expect an answer sometime next week as this week most of our team are busy at CVPR.

**Comment by victorhcm** [comment]
Hi @willprice, thank you! That was already helpful. My question is because I was wondering if we could use the object bounding boxes for action recognition. This would be very interesting, as just few datasets provide object tracks (such as the YouCook1 dataset, which isn't as large in comparison).

>  Expect an answer sometime next week as this week most of our team are busy at CVPR.

Ok, thanks! Wish you and your team a great time there.

**Comment by victorhcm** [comment]
Thank you, @hazeld! That's exactly what I wanted to know.
